import type { Bid, Listing, Purchase } from "./types";

// Demo catalog shown until a Supabase project is connected. Auction end
// times are computed relative to server start so countdowns stay live.
const BASE = Date.now();
const hours = (n: number) => new Date(BASE + n * 3_600_000).toISOString();

export const demoListings: Listing[] = [
  {
    id: "d1",
    slug: "maldives-overwater-villa",
    title: "Seven Nights in an Overwater Villa, South Ari Atoll",
    location: "South Ari Atoll",
    country: "Maldives",
    category: "beach",
    nights: 7,
    guests: 2,
    description:
      "A glass-floored villa suspended over a private lagoon, with a personal butler, sunset dolphin cruise, and seaplane transfers from Malé. Breakfast arrives by canoe; the house reef is forty feet from your deck.",
    inclusions: [
      "7 nights, overwater pool villa",
      "Round-trip seaplane transfers",
      "Daily breakfast and dinner for two",
      "Sunset dolphin cruise",
      "60-minute couples spa treatment",
    ],
    retailValue: 24500,
    startingBid: 6500,
    currentBid: 11750,
    bidCount: 23,
    bidIncrement: 250,
    buyNowPrice: 18900,
    endsAt: hours(38),
    image: "/art/maldives.svg",
    vendor: "Atoll Private Collection",
    featured: true,
    status: "live",
  },
  {
    id: "d2",
    slug: "santorini-cliffside-suite",
    title: "Cliffside Cave Suite with Caldera Plunge Pool, Oia",
    location: "Oia, Santorini",
    country: "Greece",
    category: "beach",
    nights: 5,
    guests: 2,
    description:
      "Carved into the caldera cliff, this whitewashed suite opens onto a private terrace and heated plunge pool facing the Aegean. Includes a catamaran day sail and a private wine tasting in a 17th-century canava.",
    inclusions: [
      "5 nights, cave suite with plunge pool",
      "Private catamaran day sail with lunch",
      "Canava wine tasting for two",
      "Airport transfers",
      "Daily Greek breakfast",
    ],
    retailValue: 12800,
    startingBid: 3400,
    currentBid: 6200,
    bidCount: 17,
    bidIncrement: 200,
    buyNowPrice: 9900,
    endsAt: hours(14),
    image: "/art/santorini.svg",
    vendor: "Aegean House",
    featured: true,
    status: "live",
  },
  {
    id: "d3",
    slug: "serengeti-migration-safari",
    title: "Six-Night Great Migration Safari, Serengeti",
    location: "Serengeti",
    country: "Tanzania",
    category: "safari",
    nights: 6,
    guests: 2,
    description:
      "Follow the herds from a tented camp that moves with the migration. Twice-daily game drives with a private guide, sundowners on the kopjes, and an optional dawn balloon crossing over the plains.",
    inclusions: [
      "6 nights, luxury tented camp",
      "Private 4x4 and guide throughout",
      "All meals, house wines and spirits",
      "Hot-air balloon safari at dawn",
      "Park fees and conservation levies",
    ],
    retailValue: 31000,
    startingBid: 8000,
    currentBid: 14500,
    bidCount: 31,
    bidIncrement: 500,
    buyNowPrice: 24500,
    endsAt: hours(62),
    image: "/art/serengeti.svg",
    vendor: "Meridian Safaris",
    featured: true,
    status: "live",
  },
  {
    id: "d4",
    slug: "kyoto-ryokan-retreat",
    title: "Five Nights in a Historic Ryokan with Kaiseki, Kyoto",
    location: "Higashiyama, Kyoto",
    country: "Japan",
    category: "city",
    nights: 5,
    guests: 2,
    description:
      "A 12-room ryokan on a lantern-lit lane below Kiyomizu-dera. Tatami suites with private open-air cedar baths, nightly kaiseki dinners, a private tea ceremony, and an after-hours temple visit with a monk.",
    inclusions: [
      "5 nights, garden suite with cedar bath",
      "Nightly 9-course kaiseki dinner",
      "Private tea ceremony",
      "After-hours temple visit",
      "Rail transfers from Kansai Airport",
    ],
    retailValue: 16400,
    startingBid: 4200,
    currentBid: 7350,
    bidCount: 19,
    bidIncrement: 250,
    buyNowPrice: 12800,
    endsAt: hours(86),
    image: "/art/kyoto.svg",
    vendor: "Kansai Heritage Stays",
    featured: false,
    status: "live",
  },
  {
    id: "d5",
    slug: "napa-harvest-estate",
    title: "Harvest Week at a Private Vineyard Estate, Napa",
    location: "St. Helena, Napa Valley",
    country: "United States",
    category: "wine",
    nights: 4,
    guests: 4,
    description:
      "A four-bedroom estate amid forty acres of cabernet at harvest. Blend your own barrel with the winemaker, dine at a Michelin three-star, and tour the valley by vintage convertible.",
    inclusions: [
      "4 nights, private 4-bedroom estate",
      "Winemaker blending session and barrel",
      "Dinner for four at a 3-star Michelin",
      "Vintage car valley tour",
      "Daily chef-prepared breakfast",
    ],
    retailValue: 19800,
    startingBid: 5000,
    currentBid: 9100,
    bidCount: 14,
    bidIncrement: 250,
    buyNowPrice: 15500,
    endsAt: hours(110),
    image: "/art/napa.svg",
    vendor: "Vine & Stone Estates",
    featured: false,
    status: "live",
  },
  {
    id: "d6",
    slug: "swiss-alps-chalet",
    title: "Ski-In Chalet Week with Private Chef, Zermatt",
    location: "Zermatt",
    country: "Switzerland",
    category: "mountain",
    nights: 7,
    guests: 6,
    description:
      "A timber-and-glass chalet at the foot of the Matterhorn with ski-in access, a private chef, in-chalet spa, and a helicopter glacier landing with champagne at 13,000 feet.",
    inclusions: [
      "7 nights, 4-bedroom ski-in chalet",
      "Private chef, breakfast and dinner",
      "6-day lift passes for six",
      "Helicopter glacier landing",
      "In-chalet massage for six",
    ],
    retailValue: 42000,
    startingBid: 11000,
    currentBid: 19500,
    bidCount: 27,
    bidIncrement: 500,
    buyNowPrice: 33000,
    endsAt: hours(134),
    image: "/art/zermatt.svg",
    vendor: "Alpine Reserve",
    featured: false,
    status: "live",
  },
  {
    id: "d7",
    slug: "amalfi-coast-villa",
    title: "Five Nights in a Clifftop Villa with Boat Days, Amalfi",
    location: "Positano, Amalfi Coast",
    country: "Italy",
    category: "beach",
    nights: 5,
    guests: 4,
    description:
      "A lemon-grove villa above Positano with infinity pool and daily housekeeping. Two private boat days along the coast to Capri, a pasta masterclass on your terrace, and dinner reservations that don't exist for anyone else.",
    inclusions: [
      "5 nights, 2-bedroom clifftop villa",
      "Two full-day private boat charters",
      "Terrace pasta masterclass",
      "Priority dinner reservations",
      "Naples airport transfers",
    ],
    retailValue: 17600,
    startingBid: 4600,
    currentBid: 8050,
    bidCount: 16,
    bidIncrement: 250,
    buyNowPrice: 13900,
    endsAt: hours(50),
    image: "/art/amalfi.svg",
    vendor: "Tyrrhenian Villas",
    featured: false,
    status: "live",
  },
  {
    id: "d8",
    slug: "iceland-aurora-lodge",
    title: "Northern Lights Lodge with Glacier Lagoon, Iceland",
    location: "Vatnajökull Region",
    country: "Iceland",
    category: "adventure",
    nights: 4,
    guests: 2,
    description:
      "A glass-roofed suite under the auroral oval. Private super-jeep glacier tour, zodiac crossing of the Jökulsárlón ice lagoon, geothermal lagoon entry, and a photographer on call for the lights.",
    inclusions: [
      "4 nights, glass-roof aurora suite",
      "Private super-jeep glacier day",
      "Ice lagoon zodiac crossing",
      "Geothermal lagoon premium entry",
      "Aurora photography session",
    ],
    retailValue: 11200,
    startingBid: 2900,
    currentBid: 5400,
    bidCount: 21,
    bidIncrement: 200,
    buyNowPrice: 8700,
    endsAt: hours(26),
    image: "/art/iceland.svg",
    vendor: "North Atlantic Lodges",
    featured: false,
    status: "live",
  },
  {
    id: "d9",
    slug: "bora-bora-lagoon-escape",
    title: "Six Nights Over the Lagoon, Bora Bora",
    location: "Bora Bora",
    country: "French Polynesia",
    category: "beach",
    nights: 6,
    guests: 2,
    description:
      "An end-of-pontoon overwater bungalow facing Mount Otemanu. Private lagoon picnic on a motu, snorkeling with rays and blacktips, and a Polynesian spa ritual in an open-air fare.",
    inclusions: [
      "6 nights, end-of-pontoon bungalow",
      "Private motu picnic day",
      "Guided lagoon snorkel safari",
      "Polynesian spa ritual for two",
      "Half-board dining",
    ],
    retailValue: 21900,
    startingBid: 5800,
    currentBid: 9950,
    bidCount: 18,
    bidIncrement: 250,
    buyNowPrice: 16800,
    endsAt: hours(158),
    image: "/art/bora-bora.svg",
    vendor: "Atoll Private Collection",
    featured: false,
    status: "live",
  },
  {
    id: "d10",
    slug: "patagonia-explorer-lodge",
    title: "Five-Night Explorer Lodge, Torres del Paine",
    location: "Torres del Paine",
    country: "Chile",
    category: "adventure",
    nights: 5,
    guests: 2,
    description:
      "An all-inclusive design lodge facing the granite towers. Choose from thirty guided excursions — the W trek's best day-hikes, horseback rides with baqueanos, and puma tracking with a naturalist.",
    inclusions: [
      "5 nights, lake-view suite",
      "All meals and open bar",
      "Daily guided excursions",
      "Puma tracking with naturalist",
      "Punta Arenas transfers",
    ],
    retailValue: 14800,
    startingBid: 3900,
    currentBid: 6800,
    bidCount: 12,
    bidIncrement: 200,
    buyNowPrice: 11500,
    endsAt: hours(182),
    image: "/art/patagonia.svg",
    vendor: "Austral Expeditions",
    featured: false,
    status: "live",
  },
  {
    id: "d11",
    slug: "paris-rive-gauche",
    title: "Four Nights on the Rive Gauche with Private Louvre",
    location: "Saint-Germain, Paris",
    country: "France",
    category: "city",
    nights: 4,
    guests: 2,
    description:
      "A balconied suite over the Seine, a private after-hours hour in the Louvre's Denon wing, table at a two-star on the Left Bank, and a dawn photography walk before the city wakes.",
    inclusions: [
      "4 nights, Seine-view suite",
      "Private after-hours Louvre visit",
      "Dinner for two, 2-star Michelin",
      "Dawn photography walk",
      "Arrival champagne and transfers",
    ],
    retailValue: 15200,
    startingBid: 4000,
    currentBid: 7600,
    bidCount: 25,
    bidIncrement: 250,
    buyNowPrice: 12400,
    endsAt: hours(8),
    image: "/art/paris.svg",
    vendor: "Maison Lumière Travel",
    featured: false,
    status: "live",
  },
  {
    id: "d12",
    slug: "dubai-desert-and-sky",
    title: "Desert Camp and Sky Suite Split Stay, Dubai",
    location: "Dubai",
    country: "United Arab Emirates",
    category: "adventure",
    nights: 5,
    guests: 2,
    description:
      "Two nights in a Bedouin-style desert camp — falconry at dawn, dune dinner under the stars — then three nights in a 60th-floor sky suite with butler, helicopter city tour included.",
    inclusions: [
      "2 nights desert camp, all-inclusive",
      "3 nights sky suite with butler",
      "Falconry and dune dinner",
      "Helicopter city tour",
      "All transfers including 4x4",
    ],
    retailValue: 13600,
    startingBid: 3600,
    currentBid: 6100,
    bidCount: 11,
    bidIncrement: 200,
    buyNowPrice: 10900,
    endsAt: hours(206),
    image: "/art/dubai.svg",
    vendor: "Gulf Meridian",
    featured: false,
    status: "live",
  },
];

export const demoBids: Bid[] = [
  {
    id: "b1",
    listingId: "d2",
    listingTitle: "Cliffside Cave Suite with Caldera Plunge Pool, Oia",
    amount: 6200,
    placedAt: hours(-3),
    leading: true,
  },
  {
    id: "b2",
    listingId: "d8",
    listingTitle: "Northern Lights Lodge with Glacier Lagoon, Iceland",
    amount: 5200,
    placedAt: hours(-26),
    leading: false,
  },
  {
    id: "b3",
    listingId: "d11",
    listingTitle: "Four Nights on the Rive Gauche with Private Louvre",
    amount: 7350,
    placedAt: hours(-49),
    leading: false,
  },
];

export const demoPurchases: Purchase[] = [
  {
    id: "p1",
    listingId: "d90",
    listingTitle: "Three Nights at a Tuscan Borgo, Val d'Orcia",
    amount: 5400,
    kind: "auction_win",
    status: "fulfilled",
    purchasedAt: hours(-31 * 24),
    buyer: "j.harper@example.com",
  },
  {
    id: "p2",
    listingId: "d91",
    listingTitle: "Whistler Peak Chalet, Five Nights",
    amount: 8900,
    kind: "buy_now",
    status: "paid",
    purchasedAt: hours(-9 * 24),
    buyer: "m.okafor@example.com",
  },
];
